### PR TITLE
Update React Native Maps to 0.22.1 for critical bugfix

### PR DESCRIPTION
**Pull request by vpontis**
### Does any other open PR do the same thing?

No.

### What issue is this PR fixing?

Fix for “The specified child already has a parent”

https://github.com/react-community/react-native-maps/pull/2545

### How did you test this PR?

I need help w/ testing this locally... Do I need to fork the expo repo and then have that forked expo repo point to this repo?

### CODE REVIEW

**Comment by sjchmiela** [comment]
Hey! Thank you for your contribution! I'm sorry I didn't see it before I updated this repository with 0.22.1 release. `expo#master` points now to the 0.22.1 release, we'll update Android runtime soon. 🙂

**Comment by vpontis** [comment]
Thanks @sjchmiela 

I think I'm confused tho, I don't see the v0.22.1 release in this repo. https://github.com/expo/react-native-maps/tree/v0.22.1 gives a 404

And in the `expo` repo it's still pointing to 0.22.0 https://github.com/expo/expo/blob/master/packages/expo/package.json

What am I missing?

**Comment by sjchmiela** [comment]
First we have to merge this PR https://github.com/expo/expo/pull/2680 and then rebuild Expo Client and Turtle shell app. 🙂 I wish to wait with this until Monday to let everyone enjoy their weekends.

**Comment by vpontis** [comment]
Ah gotcha, I didn't realize about all of those steps. Thanks @sjchmiela :)

You're doing great work

**Pull request closed without merging**
